export function getAreaByDocumentType(tipo: string): string {
  const mapping: Record<string, string> = {
    DECLARACION_JURADA_MENSUAL: 'INTENDENCIA_RECAUDACION_CONTROL_MASIVO',
    DECLARACION_JURADA_ANUAL: 'INTENDENCIA_RECAUDACION_CONTROL_MASIVO',
    RESOLUCION_FRACCIONAMIENTO: 'INTENDENCIA_RECAUDACION_CONTROL_MASIVO',
    RESOLUCION_APLAZAMIENTO: 'INTENDENCIA_RECAUDACION_CONTROL_MASIVO',
    ORDEN_PAGO_OP: 'INTENDENCIA_RECAUDACION_CONTROL_MASIVO',
    SOLICITUD_INSCRIPCION_RUC: 'INTENDENCIA_RECAUDACION_CONTROL_MASIVO',
    ACTUALIZACION_RUC: 'INTENDENCIA_RECAUDACION_CONTROL_MASIVO',
    RESOLUCION_DETERMINACION_RD: 'INTENDENCIA_RECAUDACION_CONTROL_MASIVO',
    RESOLUCION_MULTA_RM: 'INTENDENCIA_FISCALIZACION',
    REQUERIMIENTO_FISCALIZACION: 'INTENDENCIA_FISCALIZACION',
    AUDITORIA_LIBROS: 'INTENDENCIA_FISCALIZACION',
    CARTA_PRESENTACION: 'INTENDENCIA_RECAUDACION_CONTROL_MASIVO',
    NOTIFICACION_ELECTRONICA: 'INTENDENCIA_RECAUDACION_CONTROL_MASIVO',
  };
  return mapping[tipo] || 'INTENDENCIA_RECAUDACION_CONTROL_MASIVO';
}